name = "PFR"
keywords = ["math", "additive-combinatorics", "information-theory"]
defaultTargets = ["PFR"]

[leanOptions]
autoImplicit = false        # Prevent typos to be interpreted as new free variables
relaxedAutoImplicit = false
pp.unicode.fun = true       # Pretty-print lambdas as `fun a â†¦ b`
pp.proofs.withType = false  # Elide the types of proofs in terms

[[require]]
name = "LeanAPAP"
git = "https://github.com/YaelDillies/LeanAPAP.git"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "PFR"
